// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuuryivgqanfmfxknvfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1dXJ5aXZncWFuZm1meGtudmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjMxMjYsImV4cCI6MjA2NjUzOTEyNn0.HzrvCYbHBkJYXrolw3xqFCgyIzdAwvnpgzmU1O9OVn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);